### ISSUE TITLE
The Makefile 'bib' rule serves no purpose

### ISSUE THREAD

**Issue by fmitha** [VictorEijkhout/tex-by-topic#2]
The Makefile `bib` rule is

bib :
        cp ${HOME}/Projects/TeX/bib/tex.bib .

But this is unnecessary, because `tex.bib` is in the repository. And since the named source doesn't exist, The `bib` recipe fails. This is used in the `pdf` recipe, which fails too. Without the `make bib` at the beginning, the `pdf` recipe succeeds.

Suggestion: remove the `bib` target and also `make bib` from the `pdf` recipe.

I suggest reviewing the Makefile. The `bundle` recipe fails too, but I did not try to debug that.

**Comment by VictorEijkhout** [comment]
Those rules are only for the maintainer of the repo. They are now disabled.
